# Generated by Django 4.2.1 on 2025-03-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='est_day',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='見積日時'),
        ),
    ]
