# Generated by Django 4.2.1 on 2025-03-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0002_estimation_est_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='tel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='est_num',
            field=models.IntegerField(default=0, verbose_name='見積番号'),
        ),
    ]
