# Generated by Django 4.2.1 on 2025-03-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0003_estimation_tel_alter_estimation_est_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='shouhin_tatami',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='商品_たたみ袋'),
        ),
    ]
