# Generated by Django 4.2.1 on 2025-03-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0004_alter_estimation_shouhin_tatami'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='プリント色'),
        ),
        migrations.AlterField(
            model_name='print',
            name='way',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='加工方法'),
        ),
    ]
