# Generated by Django 4.2.1 on 2025-03-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0007_alter_print_est_num_alter_shouhin_est_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ユーザーID')),
                ('user_com', models.CharField(blank=True, max_length=255, null=True, verbose_name='会社名')),
            ],
        ),
    ]
